# Generated by Django 4.0.4 on 2022-06-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='delete',
            field=models.CharField(choices=[('Delete', 'Delete'), ('Keep', 'Keep')], default='Delete', max_length=6),
        ),
    ]
