# Generated by Django 4.0.4 on 2022-06-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_prod_delete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prod',
            new_name='DeleteProduct',
        ),
    ]
